---
# Source: dokuwiki/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokuwiki
  namespace: "default"
  labels:
    app.kubernetes.io/instance: dokuwiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dokuwiki
    app.kubernetes.io/version: 20230404.1.0
    helm.sh/chart: dokuwiki-14.7.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dokuwiki
      app.kubernetes.io/name: dokuwiki
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dokuwiki
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: dokuwiki
        app.kubernetes.io/version: 20230404.1.0
        helm.sh/chart: dokuwiki-14.7.2
      annotations:
    spec:
      
      automountServiceAccountToken: false
      # yamllint disable rule:indentation
      hostAliases:
        - hostnames:
          - status.localhost
          ip: 127.0.0.1
      # yamllint enable rule:indentation
      serviceAccountName: dokuwiki
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: dokuwiki
                    app.kubernetes.io/name: dokuwiki
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/os-shell:12-debian-12-r15
          imagePullPolicy: "IfNotPresent"
          command:
            - sh
            - -c
            - |
              mkdir -p "/bitnami/dokuwiki"
              chown -R "1001:1001" "/bitnami/dokuwiki"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: dokuwiki-data
              mountPath: /bitnami/dokuwiki
      containers:
        - name: dokuwiki
          image: docker.io/bitnami/dokuwiki:20230404.1.0-debian-12-r23
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: null
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: DOKUWIKI_USERNAME
              value: "admin"
            - name: DOKUWIKI_FULL_NAME
              value: "Admin"
            - name: DOKUWIKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dokuwiki
                  key: dokuwiki-password
            - name: DOKUWIKI_EMAIL
              value: "admin@baityapp.online"
            - name: DOKUWIKI_WIKI_NAME
              value: "Baity Wiki"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
          envFrom:
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /doku.php
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /doku.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: dokuwiki-data
              mountPath: /bitnami/dokuwiki
      volumes:
        - name: dokuwiki-data
          persistentVolumeClaim:
            claimName: dokuwiki
