---
# Source: dokuwiki/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dokuwiki
  namespace: "default"
  labels:
    app.kubernetes.io/instance: dokuwiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dokuwiki
    app.kubernetes.io/version: 20230404.1.0
    helm.sh/chart: dokuwiki-14.7.2
type: Opaque
data:
  
  dokuwiki-password: "MTIzNDU2ODk="
