# cmd to create key
# kubectl -n longhorn-system create secret generic backup-minio-access-keys --from-literal AWS_ACCESS_KEY_ID=EnKPCsosWwenTNTpJXs4 --from-literal AWS_SECRET_ACCESS_KEY=8TJAZBywCN09FGgxKIOzR3jLDLKUt2RXuBv0D2MR --from-literal AWS_ENDPOINTS=https://minioapi.baityapp.online

# cmd to get yaml file
# kubectl get secret -n longhorn-system backup-minio-access-keys -o yaml
# kubectl delete secret -n longhorn-system backup-minio-access-keys
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: QVBoRjU5OTdkTzNBdk1SZ21hblg=
  AWS_ENDPOINTS: aHR0cHM6Ly9taW5pb2FwaS5iYWl0eWFwcC5vbmxpbmU=
  AWS_SECRET_ACCESS_KEY: RUVBSWFTU2lGeEVrcDVUbTdOdmdMUkFLVEpKbEJOa0F2V1I3M25DVA==
kind: Secret
metadata:
  creationTimestamp: "2024-04-07T02:45:24Z"
  name: backup-minio-access-keys
  namespace: longhorn-system
  resourceVersion: "27506683"
  uid: a014e0df-25a9-4e48-9a2d-fe9e5cf34bcf
type: Opaque