kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: cassandra-weekly
  namespace: k10
spec:
  presetRef:
    name: weekly
    namespace: k10
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - cassandra
  actions:
    - action: backup
      backupParameters:
        filters:
          includeResources:
            - matchExpressions:
                - key: argocd.argoproj.io/instance
                  operator: In
                  values:
                    - cassandra
  createdBy: admin@example.com
status:
  validation: Success
