version: '3.4'
services:
  postgres:
      image: postgres:latest
      container_name: bamboo-postgressql
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_DB: bamboo
        POSTGRES_USER: bamboo
        POSTGRES_PASSWORD: 123123
      volumes:
        - postgres_data:/var/lib/postgresql/data/pgdata
      restart: always
      networks:
        - network-local

networks:
  network-local:
    driver: local

volumes:
  home_data:
    external: false
  mysql_data:
    external: false
