# huong dan: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# truoc tien login docker voi registry truoc:
# docker login harbor.baityapp.online -u loild
# check file config: cat ~/.docker/config.json

# cmd tao secret tu file config docker:
# kubectl create secret generic harbor-loild-nifi --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson -n nifi

# cmd to get yaml file
# kubectl get secret -n nifi harbor-loild-nifi -o yaml
# kubectl delete secret -n nifi harbor-loild-nifi
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuYmFpdHlhcHAub25saW5lIjogewoJCQkiYXV0aCI6ICJiRzlwYkdRNk1USXpORFUyWVVCQiIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJHVnNiMmx0Y2pveE1qTTBOVFpBUkc5amEyVnlhSFZpIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: "2024-04-24T06:54:54Z"
  name: harbor-loild-nifi
  namespace: nifi
  resourceVersion: "45339329"
  uid: 5948e891-9fdd-4a3a-b0f8-0c09eb96539d
type: kubernetes.io/dockerconfigjson