# huong dan: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# truoc tien login docker voi registry truoc:
# docker login harbor.baityapp.online -u loild
# check file config: cat ~/.docker/config.json

# cmd tao secret tu file config docker:
# kubectl create secret generic harbor-loild-atlassian --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson -n atlassian-software

# cmd to get yaml file
# kubectl get secret -n atlassian-software harbor-loild-atlassian -o yaml
# kubectl delete secret -n atlassian-software harbor-loild-atlassian
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuYmFpdHlhcHAub25saW5lIjogewoJCQkiYXV0aCI6ICJiRzlwYkdRNk1USXpORFUyWVVCQiIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJHVnNiMmx0Y2pveE1qTTBOVFpBUkc5amEyVnlhSFZpIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: "2024-04-02T07:35:07Z"
  name: harbor-loild-atlassian
  namespace: atlassian-software
  resourceVersion: "23102338"
  uid: 690869a5-a7a1-486f-a4d0-db5fd886967f
type: kubernetes.io/dockerconfigjson