# huong dan: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# truoc tien login docker voi registry truoc:
# docker login harbor.baityapp.online -u loild
# check file config: cat ~/.docker/config.json

# cmd tao secret tu file config docker:
# kubectl create secret generic harbor-loild --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson

# cmd to get yaml file
# kubectl get secret -n default harbor-loild -o yaml
# kubectl delete secret -n default harbor-loild
apiVersion: v1
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2hhcmJvci5iYWl0eWFwcC5vbmxpbmUiOnsidXNlcm5hbWUiOiJsb2lsZCIsInBhc3N3b3JkIjoiMTIzNDU2YUBBIiwiZW1haWwiOiJsb2lsZEBiYWl0eWFwcC5vbmxpbmUiLCJhdXRoIjoiYkc5cGJHUTZNVEl6TkRVMllVQkIifX19
kind: Secret
metadata:
  creationTimestamp: '2024-03-25T08:41:04Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:type: {}
      manager: kubectl-create
      operation: Update
      time: '2024-03-25T08:41:04Z'
  name: harbor-loild
  namespace: default
  resourceVersion: '15219312'
  uid: e2177558-8b01-45e0-b660-980022476410