apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k10-k10-ns-admin
  namespace: k10
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k10-ns-admin
subjects:
# - apiGroup: rbac.authorization.k8s.io
#   kind: User
#   name: k10-basic

- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k10:admins

- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k10-administrators
