apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: atlassian-software
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
status: {}
