apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
status: {}
