apiVersion: v2
appVersion: 2.8.0
dependencies:
- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 44.x.x
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.8.x
- condition: keycloak.enabled
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 9.x.x
description: Apache Pulsar Helm chart for Kubernetes
maintainers:
- name: zzzming
- name: cdbartholomew
- name: lhotari
- name: michaeljmarshall
- name: devinbost
name: pulsar
version: 3.2.3
