# kubectl get secret argocd-secret -n cicd -o yaml
# echo -n 'ndUPEah4fMlPxWISrZ8SXtqQPo3xIKjy' | base64
# bmRVUEVhaDRmTWxQeFdJU3JaOFNYdHFRUG8zeElLank=

# kubectl apply -f argocd-secret.yaml -n cicd
apiVersion: v1
data:
  admin.password: JDJhJDEwJDJSYVhwanpOWjRlNFpUS2Mybm0zUS5ZakNHVUlISmo5RHZ6cVpNaE9RYWRXWE1ScEdWYjlP
  admin.passwordMtime: MjAyNC0wNS0yMlQwMTo0NzowN1o=
  server.secretkey: YXNMZFlRNk9mUkpwK0llRDBPRGxaMzB2ZmZyQ3gwdlppbXJWaFlVUkF1OD0=
  oidc.keycloak.clientSecret: bmRVUEVhaDRmTWxQeFdJU3JaOFNYdHFRUG8zeElLank= 
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: argo
    meta.helm.sh/release-namespace: cicd
  creationTimestamp: "2024-05-22T01:47:10Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.10.4
    helm.sh/chart: argo-cd-6.7.3
  name: argocd-secret
  namespace: cicd
  resourceVersion: "70681841"
  uid: ba332b8d-1a3e-4815-aa44-629bbc58927f
type: Opaque