# cmd to create key
# kubectl -n atlassian-software create secret generic cicd-minio-access-keys --from-literal ACCESS_KEY=EnKPCsosWwenTNTpJXs4 --from-literal SECRET_KEY=8TJAZBywCN09FGgxKIOzR3jLDLKUt2RXuBv0D2MR

# cmd to get yaml file
# kubectl get secret -n atlassian-software cicd-minio-access-keys -o yaml
# kubectl delete secret -n atlassian-software cicd-minio-access-keys
apiVersion: v1
data:
  ACCESS_KEY: QVBoRjU5OTdkTzNBdk1SZ21hblg=
  SECRET_KEY: RUVBSWFTU2lGeEVrcDVUbTdOdmdMUkFLVEpKbEJOa0F2V1I3M25DVA==
kind: Secret
metadata:
  creationTimestamp: "2024-03-27T08:40:36Z"
  name: cicd-minio-access-keys
  namespace: atlassian-software
  resourceVersion: "17351111"
  uid: f5d320ac-1e88-403b-8286-89c2a6fa40e5
type: Opaque